version: 2
jobs:
  build:
    docker:
      - image: cibuilds/hugo:latest
    working_directory: ~/hugo
    environment:
      HUGO_BUILD_DIR: ~/hugo/public
    steps:
      - run: apk update && apk add git
      - checkout
      - run: git submodule sync && git submodule update --init
      - run: apk add --update python python-dev py-pip build-base
      - run: pip install awscli
      - run: HUGO_ENV=production hugo -v -d $HUGO_BUILD_DIR
      - run: htmlproofer $HUGO_BUILD_DIR --allow-hash-href --check-html --empty-alt-ignore --disable-external
      - add_ssh_keys:
          fingerprints:
            - "01:8d:34:59:c1:72:6a:a8:77:ce:a4:67:a5:58:89:9f"
      - run: echo $QQQIO_KEYSCAN >> ~/.ssh/known_hosts
      - deploy:
          name: deploy
          command: |
            if [ "${CIRCLE_BRANCH}" = "master" ]; then
              rsync -av --progress -e ssh $HUGO_BUILD_DIR ubuntu@qqqq.io:/home/ubuntu/circleci-test
            else
              echo "Not master branch, dry run only"
            fi